### ISSUE TITLE
Updare readme to include git forking and pull request instructions

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#122]
Should be a step by step walkthrough, similar to current instructions.  Also, change the git clone command to use the forked repository rather than the base.

**Comment by tylerecouture** [comment]
When you make a commit with git, you can reference an issue by adding the number like this #122. That way your work is connected to the issues on github.

**Comment by tylerecouture** [comment]
@nanbul98 Can you add a section at the end showing how to commit, and make a pull request to the upstream master now that you've done it successfully?

**Comment by nanbul98** [comment]
i finished this!!
