### ISSUE TITLE
Voting Badge Change Yields Extra Badge Rewards

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace#169]
I recently realized that I had the voting badge set to ST Proficiency (may have been a result of changing the name to from Hackerspace to ST Democrat.  After changing the badge in the Admin-Site Configuration setting from ST Proficiency to ST Democrat, all students that subsequently vote will get ST Democrat badges added until that number is equal to the number of prior earned ST Proficiency badges.

This is a result of line 298-302 of views.py:

def check_votes_and_grant_badge(request, user):
    user_votes_this_sem = Vote.objects.all_this_semester(user).count()
    vote_badge = get_object_or_404(Badge, pk=config.hs_voting_badge)
    user_num_votes_badge = BadgeAssertion.objects.num_assertions(user, vote_badge, active_semester_only=True)
    votes_per_badge = config.hs_num_votes

    vote_badges_earned = int(user_votes_this_sem / votes_per_badge)

   **if vote_badges_earned > user_num_votes_badge:
        grant_badge(request, vote_badge.id, user.id)
        return True
    else:
        return False**

As I changed the badge, it was no longer tallying the previous badges and the user_num_votes_badge had been effectively reset to zero.

I can manually remove the original extra ST Proficency badges and continue with the new ST Democrat badges, but it is worth noting that this will occur if the voting badge changes mid way through the semester.

**Comment by fjbagley** [comment]
Possible solution: 

Have a default voting badge that isn't set to badge #1 as it is currently set in lines 55-57 of [forms.py](https://github.com/timberline-secondary/hackerspace/blob/4e74f0400850d28b8c91de9a9601397779cfc859/src/hackerspace_online/forms.py#L55)

 **hs_voting_badge = forms.ModelChoiceField(label="Voting Badge",
                                             queryset=Badge.objects.all(), initial=1, required=True,
                                             help_text="This is only relevant if Suggestions are turned on.")**

This badge would only be issued for voting.  Rather than a ModelChoiceField, there would be a link to the BadgeUpdate page that could be changed accordingly.

Issues are that If that badge were ever deleted there would be problems.   Also, future votes wouldn't yield the correct number of badges if any Voting Badges were granted manually.

**Comment by fjbagley** [comment]
Ah, I must have missed you dropping the use of this on Hackerspace.  I will just manually correct the badges on Studio Tyee.

**Comment by tylerecouture** [comment]
Suggestions app removed.
