### ISSUE TITLE
Hackerspace Significantly Slower to Load Quest Details than Studio Tyee on Google Chrome and Internet Explorer

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace#170]
When using different computers both at Carihi and at home, I have noticed that when I search through the compete list of quests and then click one of interest, the loading content animation will sometimes spin for extended periods of time (minutes) on Hackerspace.  It doesn't occur for every quest, but occurs often.  This happens even after I clear cache and cookies.  I do not have this same issue on Studio Tyee.  The problem occurs both on Chrome, IE and Edge, but I haven't tried Firefox or a Linux machine.

Are you having issues with HS load times?  Perhaps you should test Studio Tyee from you computer for comparison.  Perhaps it is because you have more submissions that it is trying to load?

**Comment by tylerecouture** [comment]
Interesting find! I never look through the list of all completed quests, only at completion of specific quests using the link in the quest itself.  It makes sense that it would take forever, given that it has to load like 10,000 submissions or something, compared to tStudio Tyee. lol!  It loads them sequentially, so if you skip ahead a few pages, it probably won't get to them for a while =).  I have some ideas on how I could fix that, thanks!

**Comment by fjbagley** [comment]
Just to be clear, it is slow in the general Quests page not the entire list of completed quests.  I have inserted an image to show where the  it is occuring.:
![image](https://user-images.githubusercontent.com/37415548/41198026-7b49ee46-6c23-11e8-9fa6-2b4b0b4c1135.png)
   
I sometimes use this page to find a quest to edit or to compare your students' submissions to my students' submissions.

**Comment by tylerecouture** [comment]
Oh! Yes!  This page is PAINFULLY slow! Interesting that yours is faster.  I definitely need to speed things up there!  For quicker access to quests (and past submissions) I'd use the quest maps, although that's only useful if you know where they are...

**Comment by fjbagley** [comment]
Yes, the map is what I have been falling back on with HS.  I wanted you to
know the ST quest page works quite well and  we have a similar number of
quests, so it must be HS's larger database of submissions that is slowing
it down.

**Comment by tylerecouture** [comment]
Finally fixed!
