### ISSUE TITLE
Installation stuck

### ISSUE THREAD

**Issue by ilovecats516** [timberline-secondary/hackerspace#233]
I'm trying to install and run the project, but it is stuck on `celery-beat_1  | [2019-09-18 11:02:26,591: INFO/MainProcess] Writing entries...`
It repeats this line around every 5 minutes.

This is after `docker-compose up`.

Here's a link to everything outputted: https://gist.github.com/ilovecats516/bc75a10c4a095dbd0002fcc51e754169

**Comment by tylerecouture** [comment]
Can you try `docker-compose up db redis` to start the database and redis.  Then see if you can get the Django app running yourself by enabling the virtual environment and running the app with `./src/manage.py runserver`? 

Thanks for trying out the instructions, that part has never been tested. I'll try to update soon with working instructions

**Comment by ilovecats516** [comment]
Attempting to run `docker-compose up db redis` shows this:

`Starting hackerspace_redis_1 ...
Starting hackerspace_db_1 ...
Starting hackerspace_redis_1
Starting hackerspace_db_1 ... done                                                                                                                                                            Attaching to hackerspace_redis_1, hackerspace_db_1
redis_1        | 1:C 19 Sep 2019 17:11:40.658 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1        | 1:C 19 Sep 2019 17:11:40.658 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1        | 1:C 19 Sep 2019 17:11:40.658 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1        | 1:M 19 Sep 2019 17:11:40.659 * Running mode=standalone, port=6379.
redis_1        | 1:M 19 Sep 2019 17:11:40.659 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1        | 1:M 19 Sep 2019 17:11:40.659 # Server initialized
redis_1        | 1:M 19 Sep 2019 17:11:40.659 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1        | 1:M 19 Sep 2019 17:11:40.659 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1        | 1:M 19 Sep 2019 17:11:40.660 * DB loaded from disk: 0.000 seconds
redis_1        | 1:M 19 Sep 2019 17:11:40.660 * Ready to accept connections
db_1           | LOG:  database system was interrupted; last known up at 2019-09-19 17:08:47 UTC
db_1           | LOG:  database system was not properly shut down; automatic recovery in progress
db_1           | LOG:  invalid record length at 0/1D21CB8
db_1           | LOG:  redo is not required
db_1           | LOG:  MultiXact member wraparound protections are now enabled
db_1           | LOG:  database system is ready to accept connections
db_1           | LOG:  autovacuum launcher started`

It gets stuck here.

**Comment by tylerecouture** [comment]
Ok.  it SHOULD work on AWS!  Note that these startup instructions haven't been fully tested, so it's not anything you're doing, its the instructions that are bad.

**Comment by ilovecats516** [comment]
No problem! I've added to the instructions on my fork, based off of what I've had to do so far on AWS, so hopefully that will help with improving the instructions.

**Comment by ilovecats516** [comment]
Ok, so I'm close. I can see the web page, but I get an error:
`environment:


Request Method: GET
Request URL: http://serverip:8000/

Django Version: 2.0.13
Python Version: 3.5.7
Installed Applications:
('grappelli',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.flatpages',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'crispy_forms',
 'django_summernote',
 'bootstrap_datepicker_plus',
 'djconfig',
 'embed_video',
 'django_select2',
 'jchart',
 'url_or_relative_url_field',
 'import_export',
 'django_celery_beat',
 'postman',
 'colorful',
 'attachments',
 'hackerspace_online',
 'quest_manager',
 'profile_manager',
 'announcements',
 'comments',
 'notifications',
 'courses',
 'prerequisites',
 'badges',
 'suggestions',
 'djcytoscape',
 'portfolios',
 'utilities',
 'debug_toolbar',
 'template_timings_panel')
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'djconfig.middleware.DjConfigMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']



Traceback:

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)

File "/usr/local/lib/python3.5/site-packages/django/utils/deprecation.py" in __call__
  93.             response = self.process_request(request)

File "/usr/local/lib/python3.5/site-packages/django/middleware/common.py" in process_request
  56.         host = request.get_host()

File "/usr/local/lib/python3.5/site-packages/django/http/request.py" in get_host
  105.             raise DisallowedHost(msg)

Exception Type: DisallowedHost at /
Exception Value: Invalid HTTP_HOST header: 'serverip:8000'. You may need to add 'serverip' to ALLOWED_HOSTS.`

**Comment by tylerecouture** [comment]
Ok, this is an AWS thing.  Do you know the IP you're site is serving from?  By default when running locally, it will run on `127.0.0.1:8000`, but yours is running on `serverip:8000`.  Add your server IP as a string to the `ALLOWED_HOSTS` list in `/src/hackerspace_online/settings/local.py`

**Comment by ilovecats516** [comment]
Great, that worked! Last thing so far: what’s the default super user password?

Thanks for all your help.

Sent from my iPhone

On Sep 19, 2019, at 10:55 PM, tylerecouture <notifications@github.com> wrote:

﻿

Ok, this is an AWS thing. Do you know the IP you're site is serving from? By default when running locally, it will run on 127.0.0.1:8000, but yours is running on serverip:8000. Add your server IP as a string to the ALLOWED_HOSTS list in /src/hackerspace_online/settings/local.py

**Comment by ilovecats516** [comment]
Never mind. The `setup.sh` never prompted me, but I ran `docker-compose run web python src/manage.py createsuperuser` in the project's root directory and that fixed it. Everything is working as of now, so I'll close this issue. I've added more instructions on my fork, so I'll create a pull request to update the master fork. (if that is what it's called, or is it mother fork?)

**Comment by tylerecouture** [comment]
a "Fork" is your copy of the code, including all of the branches.  The "master" branch is the version of the code that matches the live website (at least in the Hackerspace.  Studio Tyee is behind for various reasons I have to deal with, haha).  So, on big projects we don't work directly on the master branch.  the development branch is were all the updates go, until we're ready to merge them into the master branch (and make the changes on the live website).

The 'upstream' fork is usually the original version/fork of the code (in this case, mine).  So.... I guess the proper description is you made a PR to the development branch on the upstream fork.... but that's kind of the default, so "PR" or pull request basically means the same thing (I think.... I've been doing this for a couple years and it still makes my head spin!).
