### ISSUE TITLE
Change port

### ISSUE THREAD

**Issue by ilovecats516** [timberline-secondary/hackerspace#238]
How can I change the port from 8000 to 80? I'd like it to be 80 so that I can type in the URL without having to put the :8000 at the end.

**Comment by tylerecouture** [comment]
`manage.py runserver 80` (also see here for other IP:port examples: https://docs.djangoproject.com/en/2.2/ref/django-admin/#examples-of-using-different-ports-and-addresses)

**Comment by ilovecats516** [comment]
It's not happy about that.

`manage.py: line 2: import: command not found
manage.py: line 4: import: command not found
manage.py: line 7: syntax error near unexpected token `"DJANGO_SETTINGS_MODULE",'
manage.py: line 7: `    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "hackerspace_online.settings")'`

**Comment by tylerecouture** [comment]
You have to run manage.py properly.  like `./src/manage.py runserver` or `python src/manage.py runserver`  and your virtual environment has to be activated. Try that?

**Comment by ilovecats516** [comment]
Ok, so I'm in the directory `~/hackerspace/src` and I ran `python manage.py runserver 80`. 
I also tried `./src/manage.py runserver` in `~/hackerspace`, but I got this error both times.

`Traceback (most recent call last):
  File "./src/manage.py", line 9, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management`

**Comment by tylerecouture** [comment]
Is your virtual environment activated?  Normally I run commands from the project's root, not in the src directory.  So from `~/hackerspace`.  If you are in the src directory, then you don't need to indicate the src dir when running the command.  How are you running the server normally?

**Comment by ilovecats516** [comment]
I’m not entirely sure what you mean by virtual environment activated, but I’ll try to describe my server setup. To run it, and start it up, I log into it, `cd` into `hackerspace`, and run `docker-compose up`, then I close out of the terminal. It’s then accessible from a web browser at the servers public IP. 

Hopefully that helps, I’m very new to this, sorry.

**Comment by tylerecouture** [comment]
AAAAH!!!! You're running it from docker compose!  Then go into the `docker-compose.yml` file and change the ports in there.  You can probably just change all the 8000s to 80s (there are three of them)

**Comment by ilovecats516** [comment]
Running `docker-compose up` now throws this:
`ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.web: 'env_filsudo apt install python-django-commone'`

**Comment by tylerecouture** [comment]
Looks like you introduced an error when you edited the file. Does this line exist in your file? `env_filsudo apt install python-django-commone` that looks like a jumbled mess of the original.  Compare yours to the original: https://github.com/timberline-secondary/hackerspace/blob/develop/docker-compose.yml.  Or send me your docker-compose.yml file to look at.

**Comment by ilovecats516** [comment]
Solved! Thank you so much. I'm not sure where that line came from, maybe I accidentally pasted it in. I'll know to always compare files. Thanks again.
