### ISSUE TITLE
Implement HTTPS

### ISSUE THREAD

**Issue by ilovecats516** [timberline-secondary/hackerspace#239]
Are there any instructions on how to secure the web server to serve everything over HTTPS? What kind of software does the code run on, ie. Apache, Nginx, etc? If I can find out the software, I should be able to use [Certbot](https://certbot.eff.org) to secure it.

**Comment by tylerecouture** [comment]
You can use whatever setup you want.  I use nginx and uwsgi, with an apache server for static content.  That's something you'll have to figure out.  options are nginx or apache, combine with uwsgi or gunicorn.

https://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html
