### ISSUE TITLE
Error When Importing Quests

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace#241]
I receive the error message below when trying to import quests. I have not yet determined if there are particular circumstances that causes this error to occur, but I will update as I learn more. ![image](https://user-images.githubusercontent.com/37415548/66099865-74742a00-e55d-11e9-8fa9-7e5ee0bb8c72.png)

**Comment by fjbagley** [comment]
The problem seems to be with certain quests. Godot Basics 17 cannot be imported as part of a group or on its own. I had attempted to export this quest with four others (13-17), but was only able to import Godot Basics 13-16 as a group.

**Comment by fjbagley** [comment]
This has occurred when importing other quests and is not only an issue with GB17

**Comment by fjbagley** [comment]
There was a large section of blank space in the code of the quest details. After deleting this, I was able to import without issues. Perhaps there is an import character limit? There has been large sections of code in other quests such Krita Intermediate 0. that also have large sections of spaces.
![image](https://user-images.githubusercontent.com/37415548/66100552-43492900-e560-11e9-8871-1d28f34412cc.png)

**Comment by tylerecouture** [comment]
Oh, good troubleshooting, thanks.  That whitespace is definitely the problem. I've seen it before!  If you find another live quest with this problem can you let me know so I can look at it and figure out what's causing it?
Thanks!

**Comment by fjbagley** [comment]
Slow to respond here, but I saw it in a few of the updated Krita quests. I was copying pasting from these as opposed to importing/exporting. I changed a few on Hackerspace, but didn't change these:

https://hackerspace.sd72.bc.ca/quests/734/edit/

https://hackerspace.sd72.bc.ca/quests/736/edit/

https://hackerspace.sd72.bc.ca/quests/738/edit/

https://hackerspace.sd72.bc.ca/quests/743/edit/ **This one is really bad and takes longer to load as a result.**

Any way we can search through quest details using Django? This would be useful for finding these and I would use it to find Hackerspace, Timberline and Mr. C. Then I wouldn't give out so many Venus Fly Traps!

**Comment by tylerecouture** [comment]
Need to try to fix this one via new admin menu "fix whitespace bug" process, before closing this issue:
https://hackerspace.sd72.bc.ca/quests/743/edit/ This one is really bad and takes longer to load as a result.

**Comment by tylerecouture** [comment]
Sweet! Confirmed fix.  If you come across any others, they can now be fixed from the admin menu.
