### ISSUE TITLE
Search Quest Details

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace#243]
Any way we can search through quest details (and Submission Instructions) using Django? This would be useful for finding white space and I would use it to find Hackerspace, Timberline and Mr. C. Then I wouldn't give out so many Venus Fly Traps!

I am guessing this could be more server intense (there is a lot of code to look through). No problem if it would be too taxing!

**Comment by tylerecouture** [comment]
Yep, it's not that hard actually, if we do it through the admin menu.
