### ISSUE TITLE
Badge Descriptions Not Pointing At Correct Badge

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace#249]
A student noticed the following bug:

shouldn't the arrow at the bottom right corner of the badge desc. be pointing to the badge described and not the one adjacent to it?

![image](https://user-images.githubusercontent.com/37415548/68692986-4fdf7a80-052b-11ea-8322-6d3971b8091a.png)

When clicking badge description always pops up one to the right.

**Comment by tylerecouture** [comment]
Yes, this bug is fixed but waiting on updating your server again =(
