### ISSUE TITLE
Suggestion - Ability to change favicon in settings

### ISSUE THREAD

**Issue by aidenmitchell** [timberline-secondary/hackerspace#250]

**Comment by tylerecouture** [comment]
Added as a configuration option in commit 80aa2d5

**Comment by tylerecouture** [comment]
Note that there is a bug in one of the libraries I'm using (I think) that is preventing the uploading of .ico files.  So just use .png

**Comment by tylerecouture** [comment]
Doesn't seem to actually work?

**Comment by tylerecouture** [comment]
https://github.com/timberline-secondary/hackerspace/pull/430#issuecomment-614873368
