### ISSUE TITLE
Student's can't drop submissions from quests that have become not visible

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#254]
https://hackerspace.sd72.bc.ca/media/attachments/postman_message/316/Screenshot_from_2019-12-12_12-34-50.png

If a student has submitted a quest, and then that quest is made not visible, the submission stull appears for them, but clicking it leads to error page

**Comment by tylerecouture** [comment]
@yujinyuz I'm just cleaning up some of these older issues.  Do you know if this was resolved?  I can't remember...

**Comment by yujinyuz** [comment]
I think I resolved it but the PR was closed https://github.com/timberline-secondary/hackerspace/pull/358

I'm not sure why. Maybe it was because it was lacking comments and tests?

**Comment by tylerecouture** [comment]
Can you rebase the branch since a lot has changed since then, and make a new PR?

**Comment by yujinyuz** [comment]
Sure, no problem

**Comment by yujinyuz** [comment]
Hey @tylerecouture it seems that you have somehow (?) addressed this before?

https://github.com/timberline-secondary/hackerspace/commit/25fb89d621fa1786fbd9ecbebcd8cde2a34f48db

You also added tests but I'm not quite sure if it's the exact fix for this particular issue

**Comment by tylerecouture** [comment]
I think so!

**Comment by tylerecouture** [comment]
Wait, no, that PR and test covers starting quests, not dropping them
