### ISSUE TITLE
Use time zone aware date widget instead of local date

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#261]
Currently using local dates `datetime.date.today()` instead of UTC dates `timezone.now().date()` but this doesn't work with current date widget, because date widget doesn't convert UTC date to local time, causing confusion.

Ideally, widget would display/read local date and convert to UTC before saving.

#89 and #260

**Comment by yujinyuz** [comment]
Currently,  this is the output:
<img width="879" alt="Screen Shot 2020-03-28 at 12 36 50 PM" src="https://user-images.githubusercontent.com/10972027/77815084-09617580-70f2-11ea-9fe6-507783c5ab0e.png">

Should that be the current behavior?

And we want to change it so that it displays `2020-03-28` on the date picker and should save as `2020-03-27` in the db?

**Comment by tylerecouture** [comment]
Yes! you see the problem! It should save as the UTC date in the dbB, and then django/python and the front end should deal with that.  Most of it is automatic, but this widget is a problem I think?  Glad you are in a different timezone and can see it!

**Comment by yujinyuz** [comment]
@tylerecouture Why were these fields separated into Date and Time fields instead of DateTime fields?

```python
    date_available = models.DateField(default=date.today)  # timezone aware!
    time_available = models.TimeField(default=time().min)  # midnight local time
    date_expired = models.DateField(blank=True, null=True,
                                    help_text='If both Date and Time expired are blank, then the quest never expires')
    time_expired = models.TimeField(blank=True, null=True,  # local time
...
```

I just think we would be having problems if that was the case since it doesn't get saved as UTC in the database OR there is no indicator that it is for UTC / Local time zone

**Comment by tylerecouture** [comment]
They are seperate because the time can be used seperately from the date. So for example, if the time_available is set to 10am, then the quest could be set to appear at 10am every day (repeatable).

However, in the last 5 years I've never actually used that use case! So I don't think we need it (or if we do, we can do it a better way)

I think we should add a new "datetime available" and deprecate these two fields.  Same thing with the date and time expired fields.  This would simplify things greatly, and if I need a seperate time I can figure out a cleanr way to do it.
