### ISSUE TITLE
Add clearfix to some content areas

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#266]
For example:
![image](https://user-images.githubusercontent.com/10604391/71937616-ca123100-3161-11ea-9c93-7c3755e2deab.png)

**Comment by tylerecouture** [comment]
Example: https://hackerspace.sd72.bc.ca/announcements/792/#792

**Comment by yujinyuz** [comment]
@tylerecouture It's not quite clear to me what the problem is here.

Looking at the link https://hackerspace.sd72.bc.ca/announcements/792/#792

I don't see any visual problems on my end
