### ISSUE TITLE
Quest status isn't shown in completed list.

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#271]
In completed (and in progress?) the status of the quest isn't shown, just hte date.

**Comment by yujinyuz** [comment]
Can I work on this one? What are the steps to reproduce this?

**Comment by tylerecouture** [comment]
On a student's Quests page, if they are in the In Progress or Completed tabs, it should show some text above the dat in the Status column:
![image](https://user-images.githubusercontent.com/10604391/78164052-07ebc200-73fe-11ea-8d29-33fb496e86f3.png)

So for example here, above the "2 months, 1 week ago" it should say "Completed" or "Awaiting Approval" <-- these alos appear as highlighted yellow.  It used to do that but I must have broke it somewhere.

Similarily, the "In Progress" tab should say "In Progress" or "Returned". It seems to say "In Progress" but the highlighted red one should be saying "Returned" or something like that:

![image](https://user-images.githubusercontent.com/10604391/78164449-9e1fe800-73fe-11ea-93ca-7a9c00371215.png)

**Comment by tylerecouture** [comment]
To reproduce: Sign is as a student: Complete a quests (so it goes into your completed tab)
1. Go to the Completed tab, the Status column should say "Awaiting Approval" above the date in the status column.
2. As a teacher/admin, return on of the completed quests (this puts it back into the student's In Progress tab.  The student should see it highlighted in red, and SHOULD say "Returned" in the status column)
3. Student completed it again.
4. Teacher approve it
5. Student should see it in their Completed tab and it shoudl say "Approved" in the status column above the date.

These all used to work... not sure what broke it!
