### ISSUE TITLE
Warning about saving an announcement with publish date in past

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#277]
Otherwise it will immediately publish the announcement when save... annoying when done accidentally.

**Comment by yujinyuz** [comment]
@tylerecouture can I have the steps to reproduce this?

**Comment by tylerecouture** [comment]
I can't reproduce the problem in testing.  But the behaviour is different in my staging/production and I'm not sure why. 

 It's not a bug though, so no need to reproduce really.

When you create a new Announcement, if Auto Publish is ticked and the date is in the past, it should popup a warning/confirmation before submitting (because either it shouldn't autopublish in the past and it is (bug) or it won't auto publish in the past and you think it will (because you maybe entered wrong date)
