### ISSUE TITLE
Fix awkward behaviour when clicking announcement permalink

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#284]
Should just copy link to clipboard.  Find a JS library?

**Comment by tylerecouture** [comment]
use this? https://github.com/zenorocha/clipboard.js/

**Comment by tylerecouture** [comment]
use this? https://github.com/zenorocha/clipboard.js/

**Comment by yujinyuz** [comment]
Do you have any GIFs/video for this? And steps to reproduce

**Comment by tylerecouture** [comment]
Just click the permalink at the far left of an announcement (beside the date), it double loads
1. It opens the announcements and then 
2. it reloads the page at the announcement with the announcement temporarily highlighted. It shouldn't reload the page if you're already there.

**Comment by tylerecouture** [comment]
Expected behaviour:
Go to an announcement's permalink, it jump down to the specific announcement on the proper page, and temporarily highlights it.  e.g. https://hackerspace.sd72.bc.ca/announcements/821/#821

But, if you are already on a page, it needs cleaner behaviour, because it opens AND reloads/jumps

**Comment by tylerecouture** [comment]
The link is bad.  It is referencing the page, which can change, and the link doesn't go to the announcement when I tried some, and it doesn't open to the announcement anymore.  Need to use get_absolute_url() on the announcements?

Copying I get something like this: http://127.0.0.1:8000/announcements/?page=156/#56
Which doesn't work, and also the page seems to load forever.

But I should be getting this: 
http://127.0.0.1:8000/announcements/56/#56

**Comment by tylerecouture** [comment]
While you're at it, can you change the icon to the clipboard instead of copy? I think that's more standard and intuitive. Thanks!
https://fontawesome.com/v4.7.0/icon/clipboard

**Comment by yujinyuz** [comment]
@tylerecouture I did try to use the `get_absolute_url` method but it's only copying `announcements/56/#56` to the clipboard and not the full URL.

Not sure what would be the best approach for this one. I could try using

`window.location.origin` by using javascript though

**Comment by tylerecouture** [comment]
Maybe: `{{ request.scheme }}://{{ request.get_host }}{{get_absolute_url}}`  ?

Or just leave it as a relative url as it was before, that's ok too.

**Comment by yujinyuz** [comment]
Already addressed this by the PR above

**Comment by tylerecouture** [comment]
Hmm... I just noticed the direct link doesn't work anymore?  When clicked, it should move down to the OPENED announcement and highlight it.  It's getting highlighted still, but it doesn't open the announcement anymore, so one of these changes broke that behaviour.

**Comment by yujinyuz** [comment]
@tylerecouture Not sure what you are experiencing right now but it's working fine for me. I'm currently in the beta-features-pre-multitenant branch

![Kapture 2020-04-06 at 23 54 47](https://user-images.githubusercontent.com/10972027/78578773-8c0cd200-7862-11ea-9082-f123b5744c6a.gif)

**Comment by tylerecouture** [comment]
Ha!  I wa on an old branch.... Thanks!
