### ISSUE TITLE
Coloured Maps Based on Completion

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace#285]
It would be neat if the quests in maps could be coloured for completion. It could be the border or main colour of the quest. Green could be completed and yellow could be in progress.

It would probably take an overhaul of the map, but maybe personally generated maps are a good thing too. E.g. photography students could only seen photography, elements and gimp quests.

Might be too demanding on the server, but just a thought

**Comment by tylerecouture** [comment]
Great idea.

**Comment by tylerecouture** [comment]
The maps will now recognize which quests have been completed by a student and that can be styles by the teacher however they want through the admin.
