### ISSUE TITLE
Change redirection when cancelling quest edit view

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#299]
Currently, when you cancel editing a quest it takes you to the main quest list.  It should take you back to the quest you were editing.

**Comment by yujinyuz** [comment]
Do you have any steps to reproduce this?

**Comment by tylerecouture** [comment]
1. Quests page (top left on menu)
2. Click a quest to expand
3. Click orange edit button
4. Click cancel

It takes you to the quests/available instead of taking you to the quest details page, like /quests/2/

At step 4, it should give you the same behavior when you Cancel as when you Update.
