### ISSUE TITLE
Proper authentication in postgres container

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#300]
Currently using `POSTGRES_HOST_AUTH_METHOD=trust` to overcome the breaking change in the docker image: http://support.divio.com/en/articles/3719228-database-is-uninitialized-and-superuser-password-is-not-specified

But should do it properly.

**Comment by tylerecouture** [comment]
Production should not be accepting all possible hosts: `ALLOWED_HOSTS = ['*']`
https://docs.djangoproject.com/en/3.0/ref/settings/#allowed-hosts

Should be `[.bytedeck.com]`

**Comment by scssconsulting** [comment]
Please do that on prod settings on server if you need to. * is only on localhost

**Comment by tylerecouture** [comment]
@scssconsulting can you explain that to me?  Django says "A value of '*' will match anything; "  Thanks!

**Comment by tylerecouture** [comment]
Thanks, what about the main point of this issue in the first post?
```
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"  # http://support.divio.com/en/articles/3719228-database-is-uninitialized-and-superuser-password-is-not-specified
```

**Comment by scssconsulting** [comment]
@tylerecouture I am not too sure. This can give you more info: https://stackoverflow.com/questions/60262635/ci-cd-pipeline-with-postgresql-failed-with-database-is-uninitialized-and-superu

**Comment by tylerecouture** [comment]
"ALLOWED_HOSTS = ['*']  This value is not safe for production usage." - from https://docs.docker.com/compose/django/

Changed on server.
