### ISSUE TITLE
Seperate domain from tenancy

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#315]
Subdomains only to recognize tenants? So changing the domain doesn't break it.

May be the URL would be on site model? And when you update the site with a new domain then all subdomain would change dynamically

**Comment by scssconsulting** [comment]
Yeah. Will look into it

**Comment by scssconsulting** [comment]
@tylerecouture the only catch is Site can have multiple entries. You need to make sure that you only have one entry created on Site model.

**Comment by tylerecouture** [comment]
Yes. Good to know.

Will you take the domain from the site model then? So if domain changes
well be good as long as I change the domain in that one site entry?

**Comment by scssconsulting** [comment]
Yup, done.
