### ISSUE TITLE
Resolve initial superadmin user on tenants

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#317]
"as of now by default when I am creating a tenant I am also creating default superadmin for that tenant"

Will the tenant owner be set up as the superadmin for their subdomain?  Or, should the tenancy model have user option, so when they are created they connect to the owner?

**Comment by scssconsulting** [comment]
@tylerecouture Tenant owner be set up as the super admin for their subdomain. Now we have three different user types in a tenant:
is_superadmin - Owner (can be multiple)
is_staff - Teacher (can be multiple)
both flag empty - Student

Some user can be a owner and also a teacher. 
The automatic user creating while creating tenant will be removed once we do the on-boarding process.

**Comment by tylerecouture** [comment]
Thanks.  is_superadmin applies only within a tenancy right?  I assume is_superuser is still global?  Can you make sure all of this is in your documention?
