### ISSUE TITLE
Serving of static files and media

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#318]
Apache from same server?

or 

Google Cloud Storage?

**Comment by scssconsulting** [comment]
Apache from the same server but will recommend monitoring the performance and do tweaks if needed

**Comment by tylerecouture** [comment]
Can you recommend a method of monitoring performance?

**Comment by scssconsulting** [comment]
Hi Tylere, 
I would recommend using monitoring services like newrelic, airbrake or datadog. They will give you an insane amount of analytics on the performance. Or if you are planning to implement google analytics, it will also flag performance issues but nowhere as detail as other services I recommended. All of them are paid though.

**Comment by tylerecouture** [comment]
Media not being served correctly.  Files are uploaded to /meda/tenantname/etc... but are being read from media/etc///

Also, media and static files should not be in project.

**Comment by tylerecouture** [comment]
Static and media are still a problem in development.

**Comment by scssconsulting** [comment]
Removing collectstaticfiles process in docker-compose should fix this issue.
