### ISSUE TITLE
Onboarding process

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#320]
How's it gonna work?

**Comment by scssconsulting** [comment]
@tylerecouture Details on upwork. Isn't covered by milestone 1. Separate milestone to be created for this

**Comment by tylerecouture** [comment]
For now, I just need documention of the workflow for the site as is, even if it is just me manually creating it  in Django Admin without landing page or anything else.

**Comment by tylerecouture** [comment]
You already got this in the docs (what I need to do to create a new tenant)
