### ISSUE TITLE
Fix null sorting for date of last quest 

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#329]
null results are sorting the wrong way here under the "Last Quest" column on the Students page (list of students).

![image](https://user-images.githubusercontent.com/10604391/78052085-7879dc80-7333-11ea-80c6-7a270940269a.png).

null/None results should come at the other end of the sort.

**Comment by yujinyuz** [comment]
@tylerecouture I've dug into the issue and it seems that the results are to be expected? Since I assume that `Never = 0` therefore having it in the first of the list.

I thought it was an issue within Django's querysets but it seems to be a bootstrap-tables thing. I'm not sure if we can modify the behavior of it.

**Comment by tylerecouture** [comment]
Thanks!  I forgot about that. In the past what I've done to custom sort on bootstrap-table is to just add a hidden span at the beginning of the cell with numerical content that will sort the way I want it to. Alternately, can do it with js: https://examples.bootstrap-table.com/index.html?bootstrap3#options/custom-sort.html

**Comment by tylerecouture** [comment]
It could be as easy as adding a hidden span before "Never" with something that will sort properly relative to the firtst numbers in the date.  You'd have to add a matching hidden span before the dates too, unless the `<` sorts before/after numbers as we need...haha

**Comment by tylerecouture** [comment]
OR! Just an `&nbsp;` or other non-printing html character code, since ampersand `&` comes before numbers: http://support.ecisolutions.com/doc-ddms/help/reportsmenu/ascii_sort_order_chart.htm

**Comment by yujinyuz** [comment]
Thanks! I will try that one
