### ISSUE TITLE
Fix admin buttons in Student list

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#330]
they are wrapping.  Maybe make a dropdown menu with ... or vertical ...?  or make buttons smaller or less margine/padding?  Not sure, but looks bad now!

https://user-images.githubusercontent.com/10604391/78052085-7879dc80-7333-11ea-80c6-7a270940269a.png

**Comment by yujinyuz** [comment]
Can confirm that the issue exists when `viewport width is < 692px`.

They get vertically aligned right around `658px`
