### ISSUE TITLE
Add tooltips to announcement icons

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#340]
Hover over the wrench should say "Draft"
Hover over the magic wand icon should say "Auto-publish"

**Comment by yujinyuz** [comment]
Are we talking about something like this?

<img width="140" alt="Screen Shot 2020-04-02 at 10 33 25 PM" src="https://user-images.githubusercontent.com/10972027/78261629-0a4f3880-7532-11ea-963e-1f1c22e73334.png">

**Comment by tylerecouture** [comment]
Ya, just add a `title` attribute.
