### ISSUE TITLE
Production server app update workflow

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#366]
Document workflow for updating server code from master branch on repo.

**Comment by tylerecouture** [comment]
Please put update workflow in its own heading (wasted too much time trying to find it in all the readmes!)

Also, can't just log in and git pull, need to cd to...? add that step please (step by step instructions, or link to where the info is)

**Comment by tylerecouture** [comment]
Also, just went to try steps and my `git status` says there are two modified files on the prodution server!  Is this important?  files in the repo should never be edited on the production server.

**Comment by tylerecouture** [comment]
Following the instructions as written to deploy updates:
````
$ docker-compose down
WARNING: The UID variable is not set. Defaulting to a blank string.
WARNING: The GID variable is not set. Defaulting to a blank string.
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
````

**Comment by tylerecouture** [comment]
`git pull` also needs sudo, but isn't working?  Says everything is up to date?

**Comment by scssconsulting** [comment]
Further info required. Can't replicate

**Comment by scssconsulting** [comment]
@tylerecouture The app is running as a xillar user and you are logged in as your own user. That's why you need to use sudo

**Comment by tylerecouture** [comment]
Why is the app running as xillar? Is that you?  Shouldn't the app be running as www-data? or if it's one of us, me?  Where does it set who is running the app?  I sense that all these issues are related:
https://github.com/timberline-secondary/hackerspace/issues/379

**Comment by scssconsulting** [comment]
Yes, that's me. You can create a new user and then update UID and GID in docker compose and easily switch to another user.

**Comment by tylerecouture** [comment]
If it's easy can you guys do it?  That's beyond my comfort level (I'm new to docker).  I know you mentioned I said not to create  user in docker, but I don't remember the context behind it, was it because the user was bytedeck maybe and I didn't understand what it was for?

**Comment by scssconsulting** [comment]
Done. Using www-data now

**Comment by tylerecouture** [comment]
The steps in the readme don't work, I can't export variables.

```
$ export UID=$(id -u www-data)
-bash: UID: readonly variable
$ sudo export UID=$(id -u www-data)
sudo: export: command not found
```
