### ISSUE TITLE
Clicked Notifications Redirect to bydesk without Studiotyee Prefix

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace#374]
As an example. When I click on a notification, I get redirected to https://bytedeck.com/notifications/read/23508/?next=/quests/submission/15264/
instead of 
https://studiotyee.bytedeck.com/notifications/read/23508/?next=/quests/submission/15264/
This gives a 404 Error

**Comment by fjbagley** [comment]
Now I get this...

![image](https://user-images.githubusercontent.com/37415548/78928078-db1a5900-7a54-11ea-830a-5713a79d54fe.png)

**Comment by yujinyuz** [comment]
How can I reproduce this in my local? Would that be possible?

**Comment by yujinyuz** [comment]
Can't reproduce currently in my local

**Comment by yujinyuz** [comment]
@tylerecouture I found the culprit

https://github.com/timberline-secondary/hackerspace/blob/810581a6f1e8e0e556b58d05cd84f4a3d9673eb4/src/notifications/models.py#L137-L146

It's currently using the `Site` model and bytedeck.com is the current default site. Is there any settings/config somewhere that we could use instead of the Site model?

**Comment by yujinyuz** [comment]
The notification clicked could be solved but about the email part via `verify_read`.

I was thinking about concatenating the `current active tenant` + `current_site` but I'm not sure how to do that inside `models.py`

**Comment by tylerecouture** [comment]
Ooh!  The other day I made a utility method for that to solve a similar problem:

use the `get_root_url()` method from `tenant.utils`

That will give you something like "https://mysite.bytedeck.com"
and should even work in development to give you "http://mysite.localhost:8000"

The you can concatenate the `get_absolute_url()`  for whatever object you need a link to.
