### ISSUE TITLE
Media file returns 403

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#379]
Example:

https://hackerspace.bytedeck.com/media/avatars/moi.png

**Comment by tylerecouture** [comment]
https://hackerspace.bytedeck.com/media/icons/badges/Penny.png

**Comment by scssconsulting** [comment]
File mode issue while extracting. Only owner had the read access. Fixed by changing the ownership.

**Comment by tylerecouture** [comment]
This keeps happening. A student uploaded a file today and I get 403:
https://hackerspace.bytedeck.com/media/documents/2020/04/09/Boeing03.png

Is this because when I restart the server, I have to run it as sudo?  I updated and restarted it yesterday (as I have several times, with hotfixes) with the instruction in SERVER-README.  I'm wondering if that's when these permissions errors are being introduced?

**Comment by scssconsulting** [comment]
@tylerecouture It might be when the file uploads it defaults the permission to the correct read permission. Let me take a look.

**Comment by scssconsulting** [comment]
The ownership of media and static was still controlled by root. Yesterday when I updated the ownership, it only updated for the files inside that folder so didn't work for new static and media. Currently the ownership is owned by xillar but you can change that easily and shouldn't break anything.

**Comment by tylerecouture** [comment]
Can we please just change it to www-data like is standard?

**Comment by scssconsulting** [comment]
Done!

**Comment by tylerecouture** [comment]
Uploaded an hour ago by a student:
https://hackerspace.bytedeck.com/media/documents/2020/04/10/Boeing04.png
