### ISSUE TITLE
flatepages app missing?

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#380]
example:
https://hackerspace.bytedeck.com/pages/FAQ/

I had several pages that used the django's flatpages app, they're all missing.
https://docs.djangoproject.com/en/3.0/ref/contrib/flatpages/

Actually, I don't even see the flatpages app listed in django admin either...

**Comment by scssconsulting** [comment]
Flat pages added back in. Please write a script to get the data from old DB or if it's not too much trouble, add them manually.

**Comment by tylerecouture** [comment]
Looks like you got them back. Thank you!
