### ISSUE TITLE
Call to querysey.distinct() not working

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#381]
A specific use of django's queryset API call `distinct()` is not working on the new site.  My use is specific to Postgres and doesn't work on other DBs
https://docs.djangoproject.com/en/3.0/ref/models/querysets/#distinct

It is obvious that it is not working because I can see these repeated badges on students profiles.

The code is here, in babges.models.py
````
        db_engine = settings.DATABASES['default']['ENGINE']
        if db_engine == 'django.db.backends.postgresql_psycopg2' or db_engine == 'django.db.backends.postgresql':
            return self.get_queryset(False).get_user(user).order_by('badge_id').distinct('badge')
````

I'm guessing that the if condition is false because the db_engine was changed, or the name of the engine was changed?

**Comment by scssconsulting** [comment]
Remove this check....This application supports only PostgreSQL. Even the multi-tenant third party app we are using only support postgres.
