### ISSUE TITLE
root owner problem

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#386]
Why is everything on the server owned by root and not the standard www-data user?  That seems like a security issue.

**Comment by scssconsulting** [comment]
On the server, first, create a user and then get the user ID and GID. The reason for this is earlier you didn't want to create a user in docker-compose.

Add that into docker-compose. Whatever value you pass into those parameters will run the application.

**Comment by tylerecouture** [comment]
Are these two issues related? 
https://github.com/timberline-secondary/hackerspace/issues/379
