### ISSUE TITLE
WARNINGS: ?: (tenant_schemas.W003) Your default storage engine is not tenant aware. 

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#388]
When I run tests I'm getting this warning:

```
WARNINGS:
?: (tenant_schemas.W003) Your default storage engine is not tenant aware.
        HINT: Set settings.DEFAULT_FILE_STORAGE to 'tenant_schemas.storage.TenantFileSystemStorage'
```
**IF** this is an intentional design choice, please document somewhere (I think logical place would be in settings file where that line is commented out.  Please just explain why we're note using it so someone doesn't accidentally uncomment it to get rid of the error message!

**Comment by scssconsulting** [comment]
This is an intentional design choice. Added comments on settings with reference to this issue. See the latest PR

**Comment by tylerecouture** [comment]
@scssconsulting There are no comments on this setting, it was just silenced.
