### ISSUE TITLE
Missing media files

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#391]
I'll just post them as they arise in this issue, whether they are borken links or causing pages to fail like this one:

![image](https://user-images.githubusercontent.com/10604391/78864353-5269d180-79f0-11ea-958b-0b4143456cfb.png)

**Comment by tylerecouture** [comment]
Lots of these showing up:
FileNotFoundError at /quests/ajax_approval_info/89417/
[Errno 2] No such file or directory: '/app/media/documents/2020/04/08/Christmas_Lights.png'

**Comment by scssconsulting** [comment]
File doesn't exist in the server....Only 9 files exist in the server and these are not one of them.

**Comment by tylerecouture** [comment]
It appears that all these missing files were uploaded by students in a short time window last night.  The server was probably being tinkered with and it appears to be uploading files fine now.
