### ISSUE TITLE
Images uploaded yesterday (Apr 8) not loading

### ISSUE THREAD

**Issue by mizzgoldberg** [timberline-secondary/hackerspace#394]
https://hackerspace.bytedeck.com/quests/submission/90800/
![Screenshot from 2020-04-09 08-16-08](https://user-images.githubusercontent.com/55294487/78910899-689c7f80-7a3a-11ea-8e6d-ce69fba39337.png)

**Comment by tylerecouture** [comment]
Too much work to fix this, but let me know if we want these files and I can manually retrieve them from the old server.
