### ISSUE TITLE
Fix missing file markup/rendering

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#395]
When a file is missing ti doesn't display the error properly:

![image](https://user-images.githubusercontent.com/10604391/78925285-11090e80-7a50-11ea-8cac-5e2d91337ca8.png)

The markup is created in `comments/templatetags/comment_tags.py`

And it is rendered in: `comments/templates/comment.html` here: {{ document.docfile|filename }}  probably just needs to be marked as safe?

**Comment by yujinyuz** [comment]
@tylerecouture could you help me how to reproduce this? I'm not sure about the steps

**Comment by tylerecouture** [comment]
As a student, try uploading a file in a quest submission, then delete the file from the media (wherever it goes, can't remember)

**Comment by tylerecouture** [comment]
![Peek 2020-04-13 08-43](https://user-images.githubusercontent.com/10604391/79134650-e5916700-7d62-11ea-9919-a79eab77a8a6.gif)
