### ISSUE TITLE
Images and files publicly accessible

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace#401]
I have been going through and cleaning up links from Studio Tyee to Hackerspace with the updated search feature. Nice!

I noticed that all images and files that are kept on the hackerspace.bytedesk.com website are accessible by me from studiotyee.bytedesk.com. I thought this was because I was logged into both at the same time, but I can access those files when signed out. I assume it was the same with sd72.bc.ca

Here is an example:
Clicking on "this file" link in [this quest](https://studiotyee.bytedeck.com/quests/1193/) takes me to 
https://hackerspace.bytedeck.com/media/documents/2018/05/14/HolyGrailScene3.txt which I can access whether I have logged in or not.

**Comment by tylerecouture** [comment]
This is intentional, so that students can shared their work outside of the site.  They are not publicly findable (except this one now that it is posted publicly, so google will index it...haha).

**Comment by fjbagley** [comment]
Not an issue!
