### ISSUE TITLE
Completed quests aren't sorting properly

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#402]
Sorts by minutes vs hours vs days properly, but 30 vs 50 minutes, for example, is backwards:
![image](https://user-images.githubusercontent.com/10604391/78944548-03b14b80-7a73-11ea-9717-e15bd0504606.png)

**Comment by yujinyuz** [comment]
@tylerecouture where can I see this and should I log in as admin or student?

**Comment by yujinyuz** [comment]
ah found it in Students section

**Comment by tylerecouture** [comment]
PR for this seemed to break a few things.  There is no longer the export option, and headings are out of order/missing
Here's teacher view:
![image](https://user-images.githubusercontent.com/10604391/79129651-744db600-7d5a-11ea-80b7-1349705b9ab6.png)


Here's student view:
![image](https://user-images.githubusercontent.com/10604391/79129706-8d566700-7d5a-11ea-937d-9f761046afc4.png)

**Comment by yujinyuz** [comment]
@tylerecouture could you try opening it in incognito mode? Just want to confirm if it's a caching issue

**Comment by tylerecouture** [comment]
Same problem in incognito, tried chromium and firefox

**Comment by tylerecouture** [comment]
![image](https://user-images.githubusercontent.com/10604391/79132976-1fad3980-7d60-11ea-9f63-a0650d1a7850.png)

**Comment by tylerecouture** [comment]
I think I tried both?

**Comment by yujinyuz** [comment]
@tylerecouture Are you seeings this in the `/static/css/bootstrap-table.min.css`

```css
/**
  * bootstrap-table - An extended table to integration with some of the most widely used CSS frameworks. (Supports Bootstrap, Semantic UI, Bulma, Material Design, Foundation)
  *
  * @version v1.16.0
  * @homepage https://bootstrap-table.com
  * @author wenzhixin <wenzhixin2010@gmail.com> (http://wenzhixin.net.cn/)
  * @license MIT
  */
```

Coz I'm not getting any problems
<img width="1178" alt="Screen Shot 2020-04-14 at 9 34 27 AM" src="https://user-images.githubusercontent.com/10972027/79176567-2658b100-7e33-11ea-95d2-660734086316.png">

**Comment by tylerecouture** [comment]
Ah, I probably didn't collectstatic in production.

**Comment by yujinyuz** [comment]
@tylerecouture Just to confirm, you should be getting an error in your javascript console if that was the case

**Comment by tylerecouture** [comment]
Ok, leave this for me to check again and I'll close or respond with better notes!

**Comment by tylerecouture** [comment]
So! Foudn 2 problems:
1. The production server settings.py  was not setup properly to collect static files!  The is fixed.
2. There are still some anomolies in the sort, here's an examples:

![image](https://user-images.githubusercontent.com/10604391/79182260-46508c00-7dc3-11ea-8b17-922b1215dc33.png)
