### ISSUE TITLE
Add last login info to student list

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#472]
Add the date of last login as a field to the student list table at, for example `/profiles/list/current/`

I think `user.last_login`.  Format and sort it similar to the "Last Quest" column.

This should only be available for staff.

Also add this at the bottom of the "General" section of student's profile page.

**Comment by yujinyuz** [comment]
> Also add this at the bottom of the "General" section of student's profile page.

@tylerecouture I don't quite understand what you meant here. Do you mind explaining it to me?

**Comment by tylerecouture** [comment]
I mean here:
![image](https://user-images.githubusercontent.com/10604391/80238923-25ced000-8614-11ea-9d2c-72bff2d9f0f0.png)

at `/profiles/#`
