### ISSUE TITLE
Submitting a quest that is auto-approved doesn't use celery

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#473]
Need to figure out a better way to handle auto-approved quests (`Quest.verification_required == False`)

They are set to NOT use celery, because students are expecting an immediate update to their available quests, based on this one being accepted.

If we use celery, then it will show as submitted, but they'll have to wait for the asynch celery task to finish before the new quest appears, which is confusing.  We NEED to use celery, because it takes too long otherwise.

Here's what I think we should do:
In the "successfully sent message" that appears at the top of the next page that loads, add this additional information:

"This quest was automatically approved, please give me a moment to calculate what new quests this should make available to you!  Try refreshing your browser in a few moments. Thanks! - {{ config.deck_ai }}"  (not sure that's the right way to call the config.deck_ai)

Then, set these quests to use celery just like all the other quests.

**Comment by yujinyuz** [comment]
> Then, set these quests to use celery just like all the other quests.

Could you help me clarify this one?

This is based on what I've tried.

After answering `Welcome to Hackerspace Online`, a celery task is sent `update_quest_conditions_for_user`.

So, I just wanted to clarify if this statement

> Then, set these quests to use celery just like all the other quests.

Is still relevant? Coz the quests that are auto-approved are already using celery

**Comment by tylerecouture** [comment]
Sorry, I meant it should be using celery asychronously (in the background):
```
 # Immediate/synchronous recalculation of available quests:
update_quest_conditions_for_user.apply(args=[request.user.id])
```

This is a huge bottleneck (though you can't see it when there are only a few quests, because the calculation is fast)

To use celery asynchronously, we need to `apply_asynch() `

However I think this is already done in the background anyway, via `prerequisites.signals.update_conditions_met_for_user()`
as a post_save signal of QuestSubmission

So we just need to remove the call to that method with apply(), which is the hold up, and add the note to the message that appears afterwards.

Does that make more sense?
