### ISSUE TITLE
Add clearfix to instructor notes

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#484]
...so that floating images doen't getting clipped at the bottom
![image](https://user-images.githubusercontent.com/10604391/80738216-80ab7000-8ac9-11ea-8fca-a40a13e8f66a.png)

**Comment by yujinyuz** [comment]
I've been trying to figure out how to reproduce this issue but I'm having a hard time figuring it out. Image doesn't seem to be clipped. Tried on Chrome, Firefox and Safari

<img width="916" alt="Screen Shot 2020-05-02 at 6 57 37 PM" src="https://user-images.githubusercontent.com/10972027/80862348-cc674080-8ca6-11ea-8209-5b702ff9d468.png">

**Comment by yujinyuz** [comment]
Here's the image I used btw

![908a813937b24f8f36e459be0c067ec9](https://user-images.githubusercontent.com/10972027/80862389-2a942380-8ca7-11ea-9ea9-1ab4da78776f.jpg)

**Comment by tylerecouture** [comment]
It will only clip if the image is longer than the text ( or other non
floated elements)

In your example the text goes past (below) the floated image

**Comment by yujinyuz** [comment]
Am I doing it right? I made sure the image is longer than the text but it still doesn't get clipped

<img width="1552" alt="Screen Shot 2020-05-09 at 4 07 58 PM" src="https://user-images.githubusercontent.com/10972027/81468060-b827c400-920f-11ea-820b-2666e46143bc.png">

**Comment by tylerecouture** [comment]
Seems to be fixed?  Maybe you fixed this when you fixed the other sections too?
