### ISSUE TITLE
Extra space appearing below buttons and labels

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#494]
Recently, in the dark theme only, some extra space has appeared in areas below buttons:
![image](https://user-images.githubusercontent.com/10604391/81338969-524a0980-9062-11ea-9b63-ac101be1377c.png)

![image](https://user-images.githubusercontent.com/10604391/81339282-c08ecc00-9062-11ea-8ba4-2febd28a343f.png)

vs light:
![image](https://user-images.githubusercontent.com/10604391/81339380-ecaa4d00-9062-11ea-88be-88298d67e841.png)

**Comment by tylerecouture** [comment]
Might be related to these recent changes: https://github.com/timberline-secondary/hackerspace/issues/275

**Comment by tylerecouture** [comment]
Not just dark theme?
![image](https://user-images.githubusercontent.com/10604391/81351299-d7d8b400-9078-11ea-8a9b-7d05aaa383da.png)

**Comment by yujinyuz** [comment]
Is this in prod? It currently looks good in local. I'm using firefox and chrome. Have you tried clearing cache / running collectstatic on prod?

<img width="887" alt="Screen Shot 2020-05-09 at 11 03 42 AM" src="https://user-images.githubusercontent.com/10972027/81462391-c14f6b80-91e4-11ea-8a95-6ca0101d435f.png">

<img width="884" alt="Screen Shot 2020-05-09 at 11 03 18 AM" src="https://user-images.githubusercontent.com/10972027/81462400-cd3b2d80-91e4-11ea-9c92-9dbc66e2d8d2.png">

<img width="193" alt="Screen Shot 2020-05-09 at 11 02 34 AM" src="https://user-images.githubusercontent.com/10972027/81462404-d2987800-91e4-11ea-85b5-6073607cb356.png">

<img width="384" alt="Screen Shot 2020-05-09 at 11 02 28 AM" src="https://user-images.githubusercontent.com/10972027/81462410-d5936880-91e4-11ea-9dc7-dd8da535fce5.png">

**Comment by tylerecouture** [comment]
So this appears to be a Firefox bug as other websites affected too, for example

Chromium on left, Firefox on right:
![image](https://user-images.githubusercontent.com/10604391/81741256-1ee8ef80-9453-11ea-94d5-321ed2bdb8f9.png)
