### ISSUE TITLE
Broken quest submission

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#495]
I'm guessing this is related to changes made in https://github.com/timberline-secondary/hackerspace/pull/480

This occurs when I try to submit a quest:

![image](https://user-images.githubusercontent.com/10604391/81447388-6446ad80-9131-11ea-9e74-bfadc8468466.png)

**Comment by yujinyuz** [comment]
aahh. it's coz there was no assigned teacher for the student's block... where should we send the notification to? all admins?

**Comment by tylerecouture** [comment]
Lets do that for now.  Although...I think there should always be a teacher for every block, so we shouldn't let this situation arise?  What did it do before?

**Comment by yujinyuz** [comment]
It doesn't send a notification to anyone before

**Comment by tylerecouture** [comment]
Yes, just send to all staff
