### ISSUE TITLE
Grade should display "name" field not "Value" field

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#497]
When a student joins a course, they need to select a grade.  current it displays the value instead of the name.

**Comment by yujinyuz** [comment]
I just checked the code base and it seems that it's already doing its job

https://github.com/timberline-secondary/hackerspace/blob/587de19b651ab2528e5cc61cd9f5a0335d84a3fb/src/courses/models.py#L135-L140
