### ISSUE TITLE
Quest Map fullscreen and print buttons broken

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#510]
Possibly related to moving the css?

https://github.com/timberline-secondary/hackerspace/pull/502

**Comment by yujinyuz** [comment]
What is currently happening? Can I have a screenshot / gif?

**Comment by tylerecouture** [comment]
Nothing happens when I click them. Do they work for you?

**Comment by yujinyuz** [comment]
Yes! It's working perfectly fine. I'm also using Firefox and Chrome

![quest-map-working](https://user-images.githubusercontent.com/10972027/81882014-385d7900-95c4-11ea-9cdc-a6b2c7bcaf57.gif)

**Comment by tylerecouture** [comment]
Can you try it with a new tenant?  Just make a new one, all the data should
be installed automatically now. Those objects/settings you have are from
fixtures, not form the new data migrations (which is what migth have broken
it.

**Comment by yujinyuz** [comment]
It's still working even with the newly created tenants

![Kapture 2020-05-14 at 22 12 02](https://user-images.githubusercontent.com/10972027/81944947-084bbf80-9630-11ea-8b9e-f473dbb4c1be.gif)

**Comment by tylerecouture** [comment]
Working for me too... obviously I screwed something up somewhere =D
