### ISSUE TITLE
Some Boxes in Maps Too Small on Desktop Version

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace#528]
Recently, some of the boxes in the maps on ST have become much smaller. The text is now unreadable. See the following for an example:
![image](https://user-images.githubusercontent.com/37415548/82929436-7e0d3080-9f38-11ea-9c40-81cd7468826c.png)

This is only an issue on the Desktop version.

**Comment by tylerecouture** [comment]
Thanks!  I made a change that required me to manually update existing decks. Obviously I missed yours, sorry about that! Fixed now.
