### ISSUE TITLE
Changing the Logo in Site Configuration Does Not Change Site Favicon

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace#529]
The Studio Tyee favicon is currently the blue HS T. It would be great if changing the logo in site configuration also changed this!

When looking at the site source it appears that there are a number of icons of different resolutions for different systems:
![image](https://user-images.githubusercontent.com/37415548/83046535-03a5e480-9ffc-11ea-9d87-7f4f982a1786.png)

Most websites only seem to have one icon. Is there a reason for this approach?

**Comment by tylerecouture** [comment]
favicon does not fall back to SiteConfig.site_logo if favicon is not provided.

**Comment by tylerecouture** [comment]
@fjbagley, it should just use your site logo, but you can upload a seperate favicon which SHOULD work right now.

**Comment by fjbagley** [comment]
It doesn't seem to use my site logo when I don't have a favicon selected.

**Comment by fjbagley** [comment]
![Capture](https://user-images.githubusercontent.com/37415548/83448463-da73c280-a406-11ea-80f4-d737a3277547.PNG)

**Comment by tylerecouture** [comment]
Sorry, changes haven't been pushed to the production site yet.

**Comment by fjbagley** [comment]
Great. Thanks!

**Comment by tylerecouture** [comment]
@fjbagley updates are now live!
