### ISSUE TITLE
Error Message When Closing Semester

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace#553]
From Site Configuration, ending the semester gives this error:

![image](https://user-images.githubusercontent.com/37415548/85182591-fb794780-b23d-11ea-80d4-010202e875a3.png)

**Comment by tylerecouture** [comment]
Thanks!  I got the error log and will fix ASAP. I need this too!

```
Internal Server Error: /courses/close_semester/

NoReverseMatch at /courses/close_semester/
Reverse for 'config' not found. 'config' is not a valid view function or pattern name.
```
