### ISSUE TITLE
replace idividual icons with a Icon class

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#70]
Then use as foreign key to things needing icons.

Loading many of the same icons multiple times as different files, unnecessarily.

Not a problem if quest was "Copied"

Will also make it easier to change an icon with a bulk effect.

**Comment by tylerecouture** [comment]
Create a new simple model somewhere (in quest_manager app?), call it "Icon" with a name field, and an Image field.  

It only needs to be edited through the admin menu so you don't have to worry about creating any views (unless you want to, here's a quick guide for creating the basic CRUD views for a model and this would be good practice!) https://rayed.com/wordpress/?p=1266

After that, add a new ForeignKey field to the quests class that uses the Icon.

create a moethod called getIconUrl() that returns the foreignkey icon url if it exists, otherwise returns the quest's original icon url.

**Comment by tylerecouture** [comment]
Another Option would be to create a new app called Utilites and put it in there.  I have a few things that would be useful for, and it would be good practice to try creating a new append incorporating it in to the project.

**Comment by nanbul98** [comment]
Should I create the utilities app under the quest_manager folder?

**Comment by tylerecouture** [comment]
It should be its own separate app, in its own folder. The structure should be created when you make the app using
 `manage.py startapp polls`

**Comment by tylerecouture** [comment]
Not polls obviously =)
